import sys
import json
import os
from datetime import datetime, timedelta, timezone


# ----------------------------
# Helpers
# ----------------------------
def parse_dt(s):
    """
    Accepts:
      - "2026-01-16 10:00:00"
      - "2026-01-16T10:00:00Z"
      - "2026-01-16T10:00:00+00:00"
    Returns timezone-aware datetime (UTC) when possible.
    """
    if not s:
        return None
    try:
        if "T" in s:
            return datetime.fromisoformat(s.replace("Z", "+00:00"))
        # assume UTC if naive format
        return datetime.strptime(s, "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
    except Exception:
        return None


def summarize_weather(weather):
    if not weather:
        return ""
    try:
        temp = weather.get("temperature_c")
        cond = weather.get("conditions")
        rain = weather.get("rain_mm")
        parts = []
        if temp is not None:
            parts.append(f"{float(temp):.1f}C")
        if cond:
            parts.append(str(cond))
        if rain:
            parts.append(f"{rain}mm rain")
        return ", ".join(parts)
    except Exception:
        return ""


def has_open_task(previous_tasks, crop_id, task_type):
    """
    Return True if there is an OPEN task of same type for same crop.
    previous_tasks item example:
      { "crop_id": 1, "type": "water", "status": "open" }
    """
    for t in previous_tasks or []:
        if t.get("crop_id") != crop_id:
            continue
        if (t.get("type") or "").lower() != (task_type or "").lower():
            continue
        status = (t.get("status") or "open").lower()
        if status in ("open", "pending", "in_progress", "todo"):
            return True
    return False


def watered_recently(last_watered_at, water_every_days, now_dt):
    """
    True => NOT due yet (skip watering task)
    False => due for watering
    """
    if not water_every_days:
        return False  # if not configured, treat as due
    last_dt = parse_dt(last_watered_at)
    if not last_dt:
        return False  # unknown last watered => treat as due

    due_at = last_dt + timedelta(days=int(water_every_days))
    return now_dt < due_at


def compute_next_watering(last_watered_at, water_every_days):
    last_dt = parse_dt(last_watered_at)
    if not last_dt or not water_every_days:
        return None
    due_at = last_dt + timedelta(days=int(water_every_days))
    return due_at.isoformat()


# Gemini-powered task helper
try:
    from google import genai
except Exception:
    genai = None

GEMINI_TASK_MODEL = os.getenv("GEMINI_TASK_MODEL", "gemini-2.0-flash")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")


def run_gemini_task(crop, weather):
    if not genai:
        return None
    if not GEMINI_API_KEY:
        return None

    weather_summary = summarize_weather(weather or {})
    prompt = f"""
You are a farming assistant that crafts a single actionable care task for the user.
Input:
- crop name: {crop.get("name")}
- stage: {crop.get("stage") or "unknown"}
- recent tasks: {crop.get("recent_tasks", [])}
- weather summary: {weather_summary or "none"}

Return JSON with keys: title, description, type, priority, due_in_hours, reason.
Use short sentences, focus on what to do next, and avoid asking questions.
If nothing actionable, return description 'Monitor plant and report back.' and priority 'low'.
""".strip()

    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
        resp = client.models.generate_content(
            model=GEMINI_TASK_MODEL,
            contents=[{"text": prompt}],
        )
        data = json.loads(resp.text or "{}")
    except Exception as exc:
        return None

    if not data.get("title"):
        return None

    return {
        "title": data.get("title"),
        "description": data.get("description", ""),
        "type": data.get("type") or "general",
        "priority": data.get("priority") or "medium",
        "due_in_hours": int(data.get("due_in_hours") or 24),
        "reason": data.get("reason", "Generated by AI"),
        "analysis_source": "gemini",
    }


# ----------------------------
# Task rules (based on your original)
# ----------------------------
def determine_base_task(plant_name, stage, weather):
    """
    Returns a task dict like your original determine_task() :contentReference[oaicite:1]{index=1}
    """
    stage_l = (stage or "").lower()
    temp = weather.get("temperature_c") if weather else None
    rain = weather.get("rain_mm") if weather else 0

    # Weather-based tasks
    if temp is not None:
        if temp > 32:
            return {
                "title": f"Protect {plant_name} from heat",
                "description": f"Hot spell: {temp}C. Add shade, water early morning/evening, and pause fertilizing until temps drop.",
                "type": "weather",
                "priority": "high",
                "due_in_hours": 6,
                "reason": "High temperature detected",
            }
        if temp < 8:
            return {
                "title": f"Protect {plant_name} from cold",
                "description": f"Cold night ahead: {temp}C. Cover plants, move pots indoors, and avoid late watering.",
                "type": "weather",
                "priority": "high",
                "due_in_hours": 12,
                "reason": "Cold weather detected",
            }

    if rain and rain > 2:
        return {
            "title": f"Adjust watering for {plant_name}",
            "description": f"Recent rain ({rain}mm). Reduce or skip watering today. Check top 2cm soil before watering.",
            "type": "water",
            "priority": "medium",
            "due_in_hours": 6,
            "reason": "Rain levels high",
        }

    # Stage-based tasks
    if "germination" in stage_l:
        return {
            "title": f"Soil moisture check - {plant_name}",
            "description": "Keep seed zone evenly moist; mist lightly if top 1 cm is dry, avoid puddles.",
            "type": "water",
            "priority": "medium",
            "due_in_hours": 24,
            "reason": "Germination stage",
        }

    if "seedling" in stage_l:
        return {
            "title": f"Light + moisture check - {plant_name}",
            "description": "Ensure seedlings get 6-8 hours of light; water lightly if top layer is dry.",
            "type": "care",
            "priority": "medium",
            "due_in_hours": 24,
            "reason": "Seedling stage needs monitoring",
        }

    if "vegetative" in stage_l:
        return {
            "title": f"Nutrient boost - {plant_name}",
            "description": "Apply nitrogen-rich fertilizer; keep soil evenly moist and weed-free.",
            "type": "fertilizer",
            "priority": "medium",
            "due_in_hours": 48,
            "reason": "Vegetative growth requires nutrients",
        }

    if "flowering" in stage_l:
        return {
            "title": f"Support flowers - {plant_name}",
            "description": "Avoid water stress; water in morning, gently shake stems for pollination if indoors.",
            "type": "care",
            "priority": "high",
            "due_in_hours": 48,
            "reason": "Flowering plants need stable conditions",
        }

    if "fruiting" in stage_l:
        return {
            "title": f"Fruit check - {plant_name}",
            "description": "Inspect fruits, prune yellow leaves, and deep soak every 2-3 days if soil dries.",
            "type": "care",
            "priority": "medium",
            "due_in_hours": 36,
            "reason": "Fruiting stage",
        }

    # Default fallback
    return {
        "title": f"General care - {plant_name}",
        "description": "Check soil moisture (top 2 cm), remove yellow leaves, and inspect for pests today.",
        "type": "general",
        "priority": "low",
        "due_in_hours": 48,
        "reason": "No specific condition triggered",
    }


def build_task(crop, base_task, now_dt, weather):
    due_date = now_dt + timedelta(hours=int(base_task["due_in_hours"]))
    return {
        "crop_id": crop.get("id"),
        "crop_name": crop.get("name", "Plant"),
        "stage": crop.get("stage", ""),
        "title": base_task["title"],
        "description": base_task["description"],
        "type": base_task["type"],
        "priority": base_task["priority"],
        "due_date": due_date.strftime("%Y-%m-%d %H:%M:%S"),
        "reason": base_task["reason"],
        "weather_used": weather,
        "weather_summary": summarize_weather(weather),
    }


# ----------------------------
# Main planner
# ----------------------------
def plan_for_crop(crop, weather, previous_tasks, now_dt):
    """
    Produces 0..N tasks for one crop.
    Key fix: watering interval logic.
    """
    crop_id = crop.get("id")
    name = crop.get("name", "Plant")
    stage = crop.get("stage", "")

    water_every_days = crop.get("water_every_days", 2)  # default 2 days if not provided
    last_watered_at = crop.get("last_watered_at")  # should come from DB or user action

    tasks = []

    # Try Gemini first
    base = run_gemini_task(
        {
            "id": crop_id,
            "name": name,
            "stage": stage,
            "recent_tasks": [
                {t.get("type"): t.get("title")} for t in (previous_tasks or [])
            ],
        },
        weather,
    )
    if not base:
        base = determine_base_task(name, stage, weather)

    # ---- BIG FIX: handle water tasks by schedule ----
    if base["type"] == "water":
        # 1) If already has open water task => skip
        if has_open_task(previous_tasks, crop_id, "water"):
            return []

        # 2) If not due yet (water every N days and last watered recently) => skip watering
        if watered_recently(last_watered_at, water_every_days, now_dt):
            # Not due: return a helpful non-watering reminder instead (optional)
            next_due = compute_next_watering(last_watered_at, water_every_days)
            # You can return empty list instead; I’ll return a low-priority info task to avoid silence:
            if not has_open_task(previous_tasks, crop_id, "general"):
                info = {
                    "title": f"Watering not due for {name}",
                    "description": f"Last watered: {last_watered_at}. Next watering due around: {next_due}. Check soil only if very dry.",
                    "type": "general",
                    "priority": "low",
                    "due_in_hours": 24,
                    "reason": f"Water every {water_every_days} days; not due yet",
                }
                tasks.append(build_task(crop, info, now_dt, weather))
            return tasks

        # 3) Due: create watering task
        tasks.append(build_task(crop, base, now_dt, weather))
        return tasks

    # ---- Non-water tasks: still dedupe by open task type ----
    if has_open_task(previous_tasks, crop_id, base["type"]):
        return []

    tasks.append(build_task(crop, base, now_dt, weather))
    return tasks


def main():
    try:
        raw = sys.stdin.read()
        data = json.loads(raw or "{}")

        weather = data.get("weather", {}) or {}
        crops = data.get("crops", []) or []
        previous_tasks = data.get("previous_tasks", []) or []

        now_dt = parse_dt(data.get("now")) or datetime.now(timezone.utc)

        all_tasks = []
        for crop in crops:
            all_tasks.extend(plan_for_crop(crop, weather, previous_tasks, now_dt))

        output = {
            "tasks": all_tasks,
            "weather_used": weather,
            "weather_summary": summarize_weather(weather),
            "generated_at": now_dt.isoformat(),
        }

        sys.stdout.write(json.dumps(output))
        sys.stdout.flush()

    except Exception as e:
        sys.stdout.write(json.dumps({"error": str(e)}))
        sys.stdout.flush()


if __name__ == "__main__":
    main()
